server:
  port: 1028

spring:
  application:
    name: cloud-feign

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1025/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true

ribbon:
  # 配置饥饿加载
  eager-load:
    enabled: true
    # 多个用,分隔
    clients: cloud-provider
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
logging:
  level:
    com.springcloud.feign.client.InfoFeignClient: debug

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: 'hystrix.stream'



